# Generated by Django 5.2.7 on 2025-10-29 09:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('catalyst', 'Catalyst Switch'), ('nexus', 'Nexus Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='devices.area')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='devices.organization')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('management_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image_version', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.area')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.devicerole')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.devicetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.organization')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.platform')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_text', models.TextField(help_text='Full configuration text')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='devices.device')),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled')], default='down', max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, help_text='Mbps', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='devices.device')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='devices.vendor'),
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='devices.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='devicetype',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='devices.vendor'),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(default=42, help_text='Rack height in U units')),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='devices.area')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'unique_together': {('name', 'site')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together={('vendor', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together={('vendor', 'model')},
        ),
    ]
