# Generated by Django 5.2.7 on 2025-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.CharField(choices=[('catalyst', 'Catalyst Switch'), ('nexus', 'Nexus Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('other', 'Other')], default='catalyst', max_length=50),
        ),
    ]
