# Generated by Django 5.2.7 on 2025-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_devicetype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='reachable_ping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='reachable_snmp',
            field=models.BooleanField(default=False),
        ),
    ]
