# Generated by Django 5.2.7 on 2025-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_last_check_device_reachable_ping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='platform',
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.CharField(choices=[('catalyst', 'Catalyst Switch'), ('nexus', 'Nexus Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('other', 'Other')], default='catalyst', max_length=50),
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
