# Generated by Django 5.2.7 on 2025-11-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_remove_device_platform_alter_devicetype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.CharField(choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('other', 'Other')], default='catalyst', max_length=50),
        ),
    ]
