# Generated by Django 5.2.7 on 2025-11-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_systemsettings_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
