# Generated by Django 5.2.7 on 2025-12-11 14:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('part_number', models.CharField(blank=True, help_text='Discrete part number (optional)', max_length=50, verbose_name='part number')),
                ('u_height', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='height (U)')),
                ('exclude_from_utilization', models.BooleanField(default=False, help_text='Devices of this type are excluded when calculating rack utilization.', verbose_name='exclude from utilization')),
                ('is_full_depth', models.BooleanField(default=True, help_text='Device consumes both front and rear rack faces.', verbose_name='is full depth')),
                ('subdevice_role', models.CharField(blank=True, choices=[('parent', 'Parent'), ('child', 'Child')], help_text='Parent devices house child devices in device bays. Leave blank if this device type is neither a parent nor a child.', max_length=50, null=True, verbose_name='parent/child status')),
                ('airflow', models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front'), ('left-to-right', 'Left to right'), ('right-to-left', 'Right to left'), ('side-to-rear', 'Side to rear'), ('rear-to-side', 'Rear to side'), ('bottom-to-top', 'Bottom to top'), ('top-to-bottom', 'Top to bottom'), ('passive', 'Passive'), ('mixed', 'Mixed')], max_length=50, null=True, verbose_name='airflow')),
                ('front_image', models.ImageField(blank=True, upload_to='devicetype-images')),
                ('rear_image', models.ImageField(blank=True, upload_to='devicetype-images')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='weight')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='RackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(choices=[(10, '10 inches'), (19, '19 inches'), (21, '21 inches'), (23, '23 inches')], default=19, help_text='Rail-to-rail width', verbose_name='width')),
                ('u_height', models.PositiveSmallIntegerField(default=42, help_text='Height in rack units', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='height (U)')),
                ('starting_unit', models.PositiveSmallIntegerField(default=1, help_text='Starting unit for rack', validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting unit')),
                ('desc_units', models.BooleanField(default=False, help_text='Units are numbered top-to-bottom', verbose_name='descending units')),
                ('outer_width', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (width)', null=True, verbose_name='outer width')),
                ('outer_height', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (height)', null=True, verbose_name='outer height')),
                ('outer_depth', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (depth)', null=True, verbose_name='outer depth')),
                ('outer_unit', models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='outer unit')),
                ('mounting_depth', models.PositiveSmallIntegerField(blank=True, help_text='Maximum depth of a mounted device, in millimeters. For four-post racks, this is the distance between the front and rear rails.', null=True, verbose_name='mounting depth')),
                ('max_weight', models.PositiveIntegerField(blank=True, help_text='Maximum load capacity for the rack', null=True, verbose_name='max weight')),
                ('weight_unit', models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='weight unit')),
                ('_abs_max_weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('form_factor', models.CharField(choices=[('2-post-frame', '2-post frame'), ('4-post-frame', '4-post frame'), ('4-post-cabinet', '4-post cabinet'), ('wall-frame', 'Wall-mounted frame'), ('wall-frame-vertical', 'Wall-mounted frame (vertical)'), ('wall-cabinet', 'Wall-mounted cabinet'), ('wall-cabinet-vertical', 'Wall-mounted cabinet (vertical)')], max_length=50, verbose_name='form factor')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
            ],
            options={
                'verbose_name': 'rack type',
                'verbose_name_plural': 'rack types',
                'ordering': ('vendor', 'model'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#888888', help_text='Optional UI color for tag badges (e.g., #FF5500)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the area. It can be hierarchical by specifying a parent area. From Global/Continent/Country/City/Building/Floor/Room', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dcim.area')),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='A unique name identifying this device within the organization.', max_length=100, null=True, verbose_name='name')),
                ('management_ip', models.GenericIPAddressField(help_text='The primary IP address used to manage this device.', protocol='IPv4', unique=True, verbose_name='management IP address')),
                ('mac_address', models.CharField(blank=True, help_text="The MAC address of the device's management interface.", max_length=17, null=True, verbose_name='MAC address')),
                ('serial_number', models.CharField(blank=True, help_text='Chassis serial number, assigned by the vendor.', max_length=50, null=True, verbose_name='serial number')),
                ('inventory_number', models.CharField(blank=True, help_text='An internal inventory or asset tag number.', max_length=100, null=True, verbose_name='inventory number')),
                ('is_stacked', models.BooleanField(default=False, help_text='Indicates whether this device is part of a stack or chassis.', verbose_name='is stacked')),
                ('position', models.DecimalField(blank=True, decimal_places=1, help_text='The lowest-numbered unit occupied by the device', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100.5)], verbose_name='position (U)')),
                ('face', models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], max_length=5, null=True, verbose_name='rack face')),
                ('platform', models.CharField(blank=True, choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('unknown', 'Unknown Platform')], default='unknown', max_length=100, null=True)),
                ('airflow', models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front'), ('left-to-right', 'Left to right'), ('right-to-left', 'Right to left'), ('side-to-rear', 'Side to rear'), ('rear-to-side', 'Rear to side'), ('bottom-to-top', 'Bottom to top'), ('top-to-bottom', 'Top to bottom'), ('passive', 'Passive'), ('mixed', 'Mixed')], max_length=50, null=True, verbose_name='airflow')),
                ('image_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='image version')),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('active', 'Active'), ('planned', 'Planned'), ('staged', 'Staged'), ('failed', 'Failed'), ('inventory', 'Inventory'), ('decommissioning', 'Decommissioning')], default='unknown', max_length=50)),
                ('uptime', models.DurationField(blank=True, help_text='Total time the device has been operational since last reboot.', null=True, verbose_name='uptime')),
                ('last_reboot', models.DateTimeField(blank=True, help_text="Timestamp of the device's last reboot.", null=True, verbose_name='last reboot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.area')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.devicerole')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.devicetype')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('config_text', models.TextField()),
                ('source', models.CharField(default='ssh', max_length=30)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='dcim.device')),
            ],
            options={
                'ordering': ['-backup_time'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRuntimeStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reachable_ping', models.BooleanField(default=False)),
                ('reachable_snmp', models.BooleanField(default=False)),
                ('reachable_ssh', models.BooleanField(default=False)),
                ('reachable_netconf', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='dcim.device')),
            ],
            options={
                'verbose_name': 'Device Runtime Status',
                'verbose_name_plural': 'Device Runtime Statuses',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('width', models.PositiveSmallIntegerField(choices=[(10, '10 inches'), (19, '19 inches'), (21, '21 inches'), (23, '23 inches')], default=19, help_text='Rail-to-rail width', verbose_name='width')),
                ('u_height', models.PositiveSmallIntegerField(default=42, help_text='Height in rack units', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='height (U)')),
                ('starting_unit', models.PositiveSmallIntegerField(default=1, help_text='Starting unit for rack', validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting unit')),
                ('desc_units', models.BooleanField(default=False, help_text='Units are numbered top-to-bottom', verbose_name='descending units')),
                ('outer_width', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (width)', null=True, verbose_name='outer width')),
                ('outer_height', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (height)', null=True, verbose_name='outer height')),
                ('outer_depth', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (depth)', null=True, verbose_name='outer depth')),
                ('outer_unit', models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='outer unit')),
                ('mounting_depth', models.PositiveSmallIntegerField(blank=True, help_text='Maximum depth of a mounted device, in millimeters. For four-post racks, this is the distance between the front and rear rails.', null=True, verbose_name='mounting depth')),
                ('max_weight', models.PositiveIntegerField(blank=True, help_text='Maximum load capacity for the rack', null=True, verbose_name='max weight')),
                ('weight_unit', models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='weight unit')),
                ('_abs_max_weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('form_factor', models.CharField(blank=True, choices=[('2-post-frame', '2-post frame'), ('4-post-frame', '4-post frame'), ('4-post-cabinet', '4-post cabinet'), ('wall-frame', 'Wall-mounted frame'), ('wall-frame-vertical', 'Wall-mounted frame (vertical)'), ('wall-cabinet', 'Wall-mounted cabinet'), ('wall-cabinet-vertical', 'Wall-mounted cabinet (vertical)')], max_length=50, null=True, verbose_name='form factor')),
                ('facility_id', models.CharField(blank=True, help_text='Locally-assigned identifier', max_length=50, null=True, verbose_name='facility ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('available', 'Available'), ('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=50, verbose_name='status')),
                ('serial', models.CharField(blank=True, max_length=50, verbose_name='serial number')),
                ('airflow', models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front')], max_length=50, null=True, verbose_name='airflow')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='dcim.area')),
                ('rack_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='dcim.racktype')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'unique_together': {('name', 'area')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.rack'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='dcim.organization')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ('organization__name', 'name'),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(help_text='Site where this device is installed.', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='area',
            name='site',
            field=models.ForeignKey(help_text='Site that contains this area.', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='dcim.site'),
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='devices', to='dcim.tag'),
        ),
        migrations.AddField(
            model_name='racktype',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rack_types', to='dcim.vendor'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='dcim.vendor'),
        ),
        migrations.CreateModel(
            name='DeviceModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dcim.device')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='dcim.vendor')),
            ],
            options={
                'verbose_name': 'Device Module',
                'verbose_name_plural': 'Device Modules',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.vendor'),
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('subnet', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid subnet in CIDR notation (e.g., 10.228.0.0/24)', regex='^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}$')])),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('usage_area', models.CharField(choices=[('ACI', 'ACI'), ('Campus', 'Campus'), ('Management', 'Management'), ('PostPro', 'PostPro'), ('Autark', 'Autark'), ('BTSU', 'BTSU'), ('IP-Telefine', 'IP-Telefone'), ('Frei', 'Frei'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='dcim.site')),
            ],
            options={
                'ordering': ['site', 'vlan_id'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled'), ('connected', 'Connected'), ('notconnected', 'Not Connected'), ('err-disabled', 'Err-Disabled')], default='down', max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, help_text='Mbps', null=True)),
                ('is_trunk', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='dcim.device')),
                ('access_vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_interfaces', to='dcim.vlan')),
                ('trunk_vlans', models.ManyToManyField(blank=True, related_name='trunk_interfaces', to='dcim.vlan')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('site', 'name', 'parent')},
        ),
        migrations.AddConstraint(
            model_name='racktype',
            constraint=models.UniqueConstraint(fields=('vendor', 'model'), name='dcim_racktype_unique_vendor_model'),
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together={('vendor', 'model')},
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('site', 'vlan_id')},
        ),
    ]
