# Generated by Django 5.2.7 on 2025-11-28 07:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('other', 'Other')], default='iosxe', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dcim.area')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='dcim.organization')),
            ],
            options={
                'verbose_name_plural': 'Areas',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('management_ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory_number', models.CharField(blank=True, max_length=100, null=True)),
                ('site', models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn'), ('Gemeinsam', 'Gemeinsam')], default='Gemeinsam', max_length=50)),
                ('image_version', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.area')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.devicerole')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.devicetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dcim.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_text', models.TextField(help_text='Full configuration text')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='dcim.device')),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
            },
        ),
        migrations.CreateModel(
            name='DeviceRuntimeStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reachable_ping', models.BooleanField(default=False)),
                ('reachable_snmp', models.BooleanField(default=False)),
                ('reachable_ssh', models.BooleanField(default=False)),
                ('reachable_netconf', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(blank=True, null=True)),
                ('uptime', models.DurationField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runtime', to='dcim.device')),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(default=42, help_text='Rack height in U units')),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='dcim.area')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'unique_together': {('name', 'area')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.rack'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='dcim.vendor'),
        ),
        migrations.CreateModel(
            name='DeviceModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='dcim.device')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='dcim.vendor')),
            ],
            options={
                'verbose_name': 'Device Module',
                'verbose_name_plural': 'Device Modules',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.vendor'),
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn'), ('Gemeinsam', 'Gemeinsam')], max_length=50)),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('subnet', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid subnet in CIDR notation (e.g., 10.228.0.0/24)', regex='^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}$')])),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('usage_area', models.CharField(choices=[('ACI', 'ACI'), ('Campus', 'Campus'), ('Management', 'Management'), ('PostPro', 'PostPro'), ('Autark', 'Autark'), ('BTSU', 'BTSU'), ('IP-Telefine', 'IP-Telefone'), ('Frei', 'Frei'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site', 'vlan_id'],
                'unique_together': {('site', 'vlan_id')},
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled')], default='down', max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, help_text='Mbps', null=True)),
                ('is_trunk', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='dcim.device')),
                ('access_vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_interfaces', to='dcim.vlan')),
                ('trunk_vlans', models.ManyToManyField(blank=True, related_name='trunk_interfaces', to='dcim.vlan')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together={('vendor', 'model')},
        ),
    ]
