# Generated by Django 5.2.7 on 2025-12-01 09:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='height',
        ),
        migrations.AddField(
            model_name='device',
            name='airflow',
            field=models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front'), ('left-to-right', 'Left to right'), ('right-to-left', 'Right to left'), ('side-to-rear', 'Side to rear'), ('rear-to-side', 'Rear to side'), ('bottom-to-top', 'Bottom to top'), ('top-to-bottom', 'Top to bottom'), ('passive', 'Passive'), ('mixed', 'Mixed')], max_length=50, null=True, verbose_name='airflow'),
        ),
        migrations.AddField(
            model_name='device',
            name='face',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], max_length=5, null=True, verbose_name='rack face'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_stacked',
            field=models.BooleanField(default=False, help_text='Indicates whether this device is part of a stack or chassis.', verbose_name='is stacked'),
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(blank=True, choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('other', 'Other')], default='unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='position',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='The lowest-numbered unit occupied by the device', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100.5)], verbose_name='position (U)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='airflow',
            field=models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front'), ('left-to-right', 'Left to right'), ('right-to-left', 'Right to left'), ('side-to-rear', 'Side to rear'), ('rear-to-side', 'Rear to side'), ('bottom-to-top', 'Bottom to top'), ('top-to-bottom', 'Top to bottom'), ('passive', 'Passive'), ('mixed', 'Mixed')], max_length=50, null=True, verbose_name='airflow'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='exclude_from_utilization',
            field=models.BooleanField(default=False, help_text='Devices of this type are excluded when calculating rack utilization.', verbose_name='exclude from utilization'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='front_image',
            field=models.ImageField(blank=True, upload_to='devicetype-images'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='is_full_depth',
            field=models.BooleanField(default=True, help_text='Device consumes both front and rear rack faces.', verbose_name='is full depth'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='part_number',
            field=models.CharField(blank=True, help_text='Discrete part number (optional)', max_length=50, verbose_name='part number'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='rear_image',
            field=models.ImageField(blank=True, upload_to='devicetype-images'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='subdevice_role',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('child', 'Child')], help_text='Parent devices house child devices in device bays. Leave blank if this device type is neither a parent nor a child.', max_length=50, null=True, verbose_name='parent/child status'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='u_height',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4, verbose_name='height (U)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='rack',
            name='_abs_max_weight',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='airflow',
            field=models.CharField(blank=True, choices=[('front-to-rear', 'Front to rear'), ('rear-to-front', 'Rear to front')], max_length=50, null=True, verbose_name='airflow'),
        ),
        migrations.AddField(
            model_name='rack',
            name='desc_units',
            field=models.BooleanField(default=False, help_text='Units are numbered top-to-bottom', verbose_name='descending units'),
        ),
        migrations.AddField(
            model_name='rack',
            name='facility_id',
            field=models.CharField(blank=True, help_text='Locally-assigned identifier', max_length=50, null=True, verbose_name='facility ID'),
        ),
        migrations.AddField(
            model_name='rack',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('2-post-frame', '2-post frame'), ('4-post-frame', '4-post frame'), ('4-post-cabinet', '4-post cabinet'), ('wall-frame', 'Wall-mounted frame'), ('wall-frame-vertical', 'Wall-mounted frame (vertical)'), ('wall-cabinet', 'Wall-mounted cabinet'), ('wall-cabinet-vertical', 'Wall-mounted cabinet (vertical)')], max_length=50, null=True, verbose_name='form factor'),
        ),
        migrations.AddField(
            model_name='rack',
            name='max_weight',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum load capacity for the rack', null=True, verbose_name='max weight'),
        ),
        migrations.AddField(
            model_name='rack',
            name='mounting_depth',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum depth of a mounted device, in millimeters. For four-post racks, this is the distance between the front and rear rails.', null=True, verbose_name='mounting depth'),
        ),
        migrations.AddField(
            model_name='rack',
            name='outer_depth',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (depth)', null=True, verbose_name='outer depth'),
        ),
        migrations.AddField(
            model_name='rack',
            name='outer_height',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (height)', null=True, verbose_name='outer height'),
        ),
        migrations.AddField(
            model_name='rack',
            name='outer_unit',
            field=models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='outer unit'),
        ),
        migrations.AddField(
            model_name='rack',
            name='outer_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (width)', null=True, verbose_name='outer width'),
        ),
        migrations.AddField(
            model_name='rack',
            name='serial',
            field=models.CharField(blank=True, max_length=50, verbose_name='serial number'),
        ),
        migrations.AddField(
            model_name='rack',
            name='starting_unit',
            field=models.PositiveSmallIntegerField(default=1, help_text='Starting unit for rack', validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting unit'),
        ),
        migrations.AddField(
            model_name='rack',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('available', 'Available'), ('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=50, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='rack',
            name='u_height',
            field=models.PositiveSmallIntegerField(default=42, help_text='Height in rack units', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='height (U)'),
        ),
        migrations.AddField(
            model_name='rack',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='weight unit'),
        ),
        migrations.AddField(
            model_name='rack',
            name='width',
            field=models.PositiveSmallIntegerField(choices=[(10, '10 inches'), (19, '19 inches'), (21, '21 inches'), (23, '23 inches')], default=19, help_text='Rail-to-rail width', verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='Name of the area. It can be hierarchical by specifying a parent area. From Global/Continent/Country/City/Building/Floor/Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='image version'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='An internal inventory or asset tag number.', max_length=100, null=True, verbose_name='inventory number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text="The MAC address of the device's management interface.", max_length=17, null=True, verbose_name='MAC address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='management_ip',
            field=models.GenericIPAddressField(help_text='The primary IP address used to manage this device.', protocol='IPv4', unique=True, verbose_name='management IP address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='A unique name identifying this device within the organization.', max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Chassis serial number, assigned by the vendor.', max_length=50, null=True, verbose_name='serial number'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('active', 'Active'), ('planned', 'Planned'), ('staged', 'Staged'), ('failed', 'Failed'), ('inventory', 'Inventory'), ('decommissioning', 'Decommissioning')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='model',
            field=models.CharField(max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled'), ('connected', 'Connected'), ('notconnected', 'Not Connected'), ('err-disabled', 'Err-Disabled')], default='down', max_length=20),
        ),
        migrations.AlterField(
            model_name='rack',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='dcim.area'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='site',
            field=models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn'), ('Gemeinsam', 'Gemeinsam')], default='Berlin', max_length=50),
        ),
        migrations.CreateModel(
            name='RackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(choices=[(10, '10 inches'), (19, '19 inches'), (21, '21 inches'), (23, '23 inches')], default=19, help_text='Rail-to-rail width', verbose_name='width')),
                ('u_height', models.PositiveSmallIntegerField(default=42, help_text='Height in rack units', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='height (U)')),
                ('starting_unit', models.PositiveSmallIntegerField(default=1, help_text='Starting unit for rack', validators=[django.core.validators.MinValueValidator(1)], verbose_name='starting unit')),
                ('desc_units', models.BooleanField(default=False, help_text='Units are numbered top-to-bottom', verbose_name='descending units')),
                ('outer_width', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (width)', null=True, verbose_name='outer width')),
                ('outer_height', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (height)', null=True, verbose_name='outer height')),
                ('outer_depth', models.PositiveSmallIntegerField(blank=True, help_text='Outer dimension of rack (depth)', null=True, verbose_name='outer depth')),
                ('outer_unit', models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='outer unit')),
                ('mounting_depth', models.PositiveSmallIntegerField(blank=True, help_text='Maximum depth of a mounted device, in millimeters. For four-post racks, this is the distance between the front and rear rails.', null=True, verbose_name='mounting depth')),
                ('max_weight', models.PositiveIntegerField(blank=True, help_text='Maximum load capacity for the rack', null=True, verbose_name='max weight')),
                ('weight_unit', models.CharField(blank=True, choices=[('mm', 'Millimeters'), ('in', 'Inches')], max_length=50, null=True, verbose_name='weight unit')),
                ('_abs_max_weight', models.PositiveBigIntegerField(blank=True, null=True)),
                ('form_factor', models.CharField(choices=[('2-post-frame', '2-post frame'), ('4-post-frame', '4-post frame'), ('4-post-cabinet', '4-post cabinet'), ('wall-frame', 'Wall-mounted frame'), ('wall-frame-vertical', 'Wall-mounted frame (vertical)'), ('wall-cabinet', 'Wall-mounted cabinet'), ('wall-cabinet-vertical', 'Wall-mounted cabinet (vertical)')], max_length=50, verbose_name='form factor')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rack_types', to='dcim.vendor')),
            ],
            options={
                'verbose_name': 'rack type',
                'verbose_name_plural': 'rack types',
                'ordering': ('vendor', 'model'),
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='dcim.racktype'),
        ),
        migrations.AddConstraint(
            model_name='racktype',
            constraint=models.UniqueConstraint(fields=('vendor', 'model'), name='dcim_racktype_unique_vendor_model'),
        ),
    ]
