# Generated by Django 5.2.7 on 2025-12-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0002_alter_rack_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=50, null=True, verbose_name='weight unit'),
        ),
        migrations.AlterField(
            model_name='racktype',
            name='weight_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], max_length=50, null=True, verbose_name='weight unit'),
        ),
    ]
