# Generated by Django 5.2.7 on 2025-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0002_remove_devicetype_category_remove_rack_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_reboot',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the device's last reboot.", null=True, verbose_name='last reboot'),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime',
            field=models.DurationField(blank=True, help_text='Total time the device has been operational since last reboot.', null=True, verbose_name='uptime'),
        ),
    ]
