# Generated by Django 5.2.7 on 2025-12-15 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_alter_rack_weight_unit_alter_racktype_weight_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='device',
            name='vendor',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='platform',
            field=models.CharField(choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('unknown', 'Unknown Platform')], default='unknown', help_text='Operating system / platform family (e.g. IOS-XE, NX-OS, Junos).', max_length=50, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='device',
            name='area',
            field=models.ForeignKey(help_text='Set once the device is physically installed.', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.area'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(help_text='Unique name identifying this device.', max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(blank=True, help_text='Rack where the device is mounted (optional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.rack'),
        ),
        migrations.AlterField(
            model_name='device',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Functional role of the device in the network (e.g. core, access, firewall, spine, leaf).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='dcim.devicerole'),
        ),
        migrations.AlterField(
            model_name='device',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Optional labels used for grouping, filtering, and automation (e.g. 'reachability_check_tag', 'datacenter', 'production').", related_name='devices', to='dcim.tag'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='vendor',
            field=models.ForeignKey(help_text='Manufacturer of this device model.', on_delete=django.db.models.deletion.PROTECT, related_name='device_type', to='dcim.vendor', verbose_name='vendor'),
        ),
    ]
