# Generated by Django 5.2.7 on 2025-12-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_site_hierarchy_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='site',
            field=models.ForeignKey(help_text='Site where this device is installed.', on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.site'),
        ),
        migrations.AlterUniqueTogether(
            name='vlan',
            unique_together={('site', 'vlan_id')},
        ),
    ]
