# Generated by Django 5.2.7 on 2025-12-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0004_remove_device_platform_remove_device_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='platform',
            field=models.CharField(choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('firewall', 'Firewall'), ('router', 'Router'), ('eos', 'Arista EOS Switche'), ('ap', 'Access Point'), ('server', 'Server'), ('unknown', 'Unknown Platform')], default='unknown', help_text='Operating system / platform family (e.g. IOS-XE, NX-OS, Junos).', max_length=50, verbose_name='platform'),
        ),
    ]
