# Generated by Django 5.2.7 on 2025-12-19 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_alter_devicetype_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this device was observed by discovery or polling', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('discovery', 'Discovery'), ('import', 'Import')], db_index=True, default='manual', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, help_text='The specific model of this device.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='dcim.devicetype'),
        ),
        migrations.AlterField(
            model_name='device',
            name='image_version',
            field=models.CharField(blank=True, help_text='The operating system version running on the device.', max_length=100, null=True, verbose_name='image version'),
        ),
    ]
