# Generated by Django 5.2.7 on 2025-12-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_alter_device_site_alter_vlan_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceruntimestatus',
            options={'verbose_name': 'Device Runtime Status', 'verbose_name_plural': 'Device Runtime Statuses'},
        ),
        migrations.AddField(
            model_name='deviceruntimestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
