# Generated by Django 5.2.7 on 2025-12-29 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0006_device_last_seen_device_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceconfiguration',
            options={'ordering': ['-collected_at']},
        ),
        migrations.RenameField(
            model_name='deviceconfiguration',
            old_name='backup_time',
            new_name='collected_at',
        ),
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='config_hash',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='dcim.deviceconfiguration'),
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='source',
            field=models.CharField(choices=[('ssh', 'SSH'), ('netconf', 'NETCONF'), ('api', 'API'), ('import', 'Import')], default='ssh', max_length=30),
        ),
        migrations.AddIndex(
            model_name='deviceconfiguration',
            index=models.Index(fields=['device', 'collected_at'], name='dcim_device_device__2d2666_idx'),
        ),
    ]
