# Generated by Codex on 2025-01-07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0007_alter_deviceconfiguration_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetype",
            name="front_svg",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="device-type-svg",
                help_text="Auto-generated flat front SVG for rack elevations.",
            ),
        ),
    ]
