# Generated by Django 5.2.7 on 2025-12-07 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0007_tag_device_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceconfiguration',
            options={'ordering': ['-backup_time']},
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='backup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='source',
            field=models.CharField(default='ssh', max_length=30),
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='config_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='deviceconfiguration',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
