# Generated by Django 5.2.7 on 2026-01-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0008_devicetype_front_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodule',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
