# Generated by Django 5.2.7 on 2025-12-07 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0008_alter_deviceconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfiguration',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
