# Generated by Django 5.2.7 on 2026-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0009_alter_devicemodule_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='default_ac_power_supply_watts',
            field=models.PositiveIntegerField(blank=True, help_text='Default power capacity of a single AC power supply for this device type.', null=True, verbose_name='default AC power supply (watts)'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Physical dimensions (L x W x H) in standard units, e.g. inches or mm.', max_length=100, null=True, verbose_name='dimensions'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='switching_capacity_gbps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total switching capacity of the device in gigabits per second.', max_digits=10, null=True, verbose_name='switching capacity (Gbps)'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the device with default power supply in kilograms.', max_digits=8, null=True, verbose_name='weight'),
        ),
    ]
