# Generated by Django 5.2.7 on 2025-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0009_remove_deviceconfiguration_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(blank=True, choices=[('ios', 'Cisco IOS Switch'), ('iosxe', 'Cisco IOS-XE Switch'), ('nxos', 'Cisco NX-OS Switch'), ('router', 'Router'), ('firewall', 'Firewall'), ('ap', 'Access Point'), ('server', 'Server'), ('unknown', 'Unknown Platform')], default='unknown', max_length=100, null=True),
        ),
    ]
