# Generated by Django 5.2.7 on 2026-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0010_devicetype_default_ac_power_supply_watts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='datasheet',
            field=models.URLField(blank=True, help_text="URL to the manufacturer's datasheet for this device type.", null=True, verbose_name='datasheet'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='forwarding_rate_mpps',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packet forwarding rate in millions of packets per second.', max_digits=10, null=True, verbose_name='forwarding rate (Mpps)'),
        ),
    ]
