# Generated by Django 5.2.7 on 2026-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0011_devicetype_datasheet_devicetype_forwarding_rate_mpps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='model',
            field=models.CharField(help_text='Model name as assigned by the vendor.', max_length=100, verbose_name='model'),
        ),
    ]
