# Generated by Django 5.2.7 on 2026-01-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0012_alter_devicetype_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Indicates whether this interface is virtual (e.g., loopback, VLAN)'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='endpoint',
            field=models.CharField(blank=True, help_text='Connected endpoint (if known)', max_length=255, null=True, verbose_name='Endpoint'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='is_trunk',
            field=models.BooleanField(default=False, help_text='Indicates whether this interface is a trunk port'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='mac_address',
            field=models.CharField(blank=True, help_text="The MAC address of the device's management interface.", max_length=17, null=True, verbose_name='MAC address'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(help_text='Name of the interface as reported by the device', max_length=100, verbose_name='Interface Name'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='speed',
            field=models.PositiveIntegerField(blank=True, help_text='Interface speed in megabits per second', null=True, verbose_name='Speed (Mbps)'),
        ),
    ]
