# Generated by Django 5.2.7 on 2026-01-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0013_interface_is_virtual_alter_interface_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='kind',
            field=models.CharField(choices=[('physical', 'Physical'), ('port-channel', 'Port-Channel'), ('svi', 'SVI'), ('loopback', 'Loopback'), ('tunnel', 'Tunnel')], db_index=True, default='physical', help_text='Normalized interface type (physical, svi, port-channel, loopback, tunnel)', max_length=20),
        ),
        migrations.AddField(
            model_name='interface',
            name='lag',
            field=models.ForeignKey(blank=True, help_text='Link Aggregation Group this interface is a member of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='dcim.interface', verbose_name='LAG'),
        ),
        migrations.AddField(
            model_name='interface',
            name='lag_mode',
            field=models.CharField(blank=True, help_text='LAG mode (e.g., active, passive, on)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='mode',
            field=models.CharField(blank=True, choices=[('L2', 'Layer 2'), ('L3', 'Layer 3')], db_index=True, help_text='Layer mode (L2 or L3)', max_length=2, null=True),
        ),
    ]
