# Generated by Django 5.2.7 on 2026-01-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0014_interface_kind_interface_lag_interface_lag_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='duplex',
            field=models.CharField(blank=True, help_text='Duplex mode as reported by the device (e.g., a-full, full, half).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='speed_mode',
            field=models.CharField(blank=True, help_text='Speed mode as reported by the device (e.g., a-1000, 1000).', max_length=20, null=True),
        ),
    ]
