# Generated by Django 5.2.7 on 2026-01-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0015_interface_duplex_speed_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='native_vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_interfaces', to='dcim.vlan'),
        ),
        migrations.AddField(
            model_name='interface',
            name='switchport_enabled',
            field=models.BooleanField(default=False, help_text='Whether this interface operates as a Layer 2 switchport'),
        ),
        migrations.AddField(
            model_name='interface',
            name='switchport_mode',
            field=models.CharField(blank=True, choices=[('access', 'Access'), ('trunk', 'Trunk'), ('dynamic', 'Dynamic'), ('dot1q-tunnel', 'Dot1Q Tunnel'), ('private-vlan', 'Private VLAN')], help_text='Switchport mode as configured on the device', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='vlan_raw',
            field=models.CharField(blank=True, help_text='Raw VLAN/switchport value from device output (debug/reference)', max_length=64),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled'), ('connected', 'Connected'), ('notconnected', 'Not Connected'), ('err-disabled', 'Err-Disabled'), ('xcvrAbsen', 'Xcvr Absence')], default='down', max_length=20),
        ),
    ]
