# Generated by Django 5.2.7 on 2026-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0016_interface_native_vlan_interface_switchport_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='occupied_units',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='List of rack unit positions currently assigned to devices', verbose_name='occupied units'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('disabled', 'Disabled'), ('connected', 'Connected'), ('notconnected', 'Not Connected'), ('err-disabled', 'Err-Disabled'), ('xcvrAbsen', 'Xcvr Absence'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], default='down', max_length=20),
        ),
    ]
