# Generated by Django 5.2.7 on 2026-01-18 12:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0017_rack_occupied_units_alter_interface_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStackMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('switch_number', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('active', 'Active'), ('standby', 'Standby'), ('master', 'Master'), ('member', 'Member'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('mac_address', models.CharField(max_length=17)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('ready', 'Ready'), ('provisioned', 'Provisioned'), ('removed', 'Removed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stack_members', to='dcim.device')),
            ],
            options={
                'ordering': ('switch_number',),
                'unique_together': {('device', 'switch_number')},
            },
        ),
    ]
