# Generated by Django 5.2.7 on 2026-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0020_alter_devicetype_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetype",
            name="eosl",
            field=models.DateField(
                blank=True,
                help_text="Last date this device type is supported by the vendor.",
                null=True,
                verbose_name="end of service life (EOSL)",
            ),
        ),
    ]
