# Generated by Django 5.2.7 on 2026-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dcim", "0021_devicetype_eosl"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodule",
            name="inventory_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
