# Generated by Django 5.2.7 on 2025-12-31 14:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0008_devicetype_front_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryFilter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname_contains', models.CharField(blank=True, help_text='Comma-separated substrings that must be present in hostname', max_length=255)),
                ('hostname_not_contains', models.CharField(blank=True, help_text='Comma-separated substrings that must NOT be present in hostname', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_filters', to='dcim.site')),
            ],
            options={
                'ordering': ['site', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveryCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('alive', models.BooleanField(default=False)),
                ('reachable_ssh', models.BooleanField(default=False)),
                ('reachable_ping', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField()),
                ('classified', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.site')),
            ],
            options={
                'unique_together': {('site', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='DiscoveryRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cidr', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('scan_method', models.CharField(choices=[('tcp', 'TCP'), ('icmp', 'ICMP')], default='tcp', max_length=10)),
                ('scan_port', models.PositiveIntegerField(default=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_ranges', to='dcim.site')),
            ],
            options={
                'unique_together': {('site', 'cidr')},
            },
        ),
    ]
