# Generated by Django 5.2.7 on 2026-03-04 15:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0019_site_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_number', models.CharField(blank=True, db_index=True, help_text='Internal inventory or asset tag number.', max_length=100, null=True, unique=True)),
                ('item_type', models.CharField(choices=[('device', 'Device'), ('module', 'Module')], default='device', max_length=16)),
                ('designation', models.CharField(help_text='General designation such as Switch, Uplink Module, or SFP.', max_length=150)),
                ('model', models.CharField(help_text='Vendor model name or free-text model description.', max_length=255)),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='Serial number assigned by the vendor.', max_length=100, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('reserved', 'Reserved'), ('installed', 'Installed'), ('rma', 'RMA'), ('retired', 'Retired')], default='in_stock', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, help_text='Optional area associated with this inventory item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='dcim.area')),
                ('site', models.ForeignKey(help_text='Site used for filtering and reporting.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='dcim.site')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='dcim.vendor')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
                'ordering': ('-created_at',),
            },
        ),
    ]
