# Generated by Django 5.2.7 on 2026-03-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_inventoryitem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='designation',
            field=models.CharField(choices=[('Switch', 'Switch'), ('Access Point', 'Access Point'), ('Uplink Module', 'Uplink Module'), ('QSFP Transceiver', 'QSFP Transceiver'), ('QSFP to SFP10G Adapter', 'QSFP to SFP10G Adapter'), ('SFP+ Transceiver', 'SFP+ Transceiver'), ('SFP Transceiver', 'SFP Transceiver')], default='Switch', help_text='Select the component designation.', max_length=150),
        ),
    ]
