# Generated by Django 5.2.7 on 2025-11-28 07:33

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn'), ('Gemeinsam', 'Gemeinsam')], max_length=50, unique=True)),
                ('ssh_username', models.CharField(max_length=100)),
                ('ssh_password', encrypted_model_fields.fields.EncryptedCharField()),
                ('ssh_port', models.IntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tacacs_enabled', models.BooleanField(default=False)),
                ('tacacs_server_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('tacacs_port', models.PositiveIntegerField(default=49)),
                ('tacacs_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('tacacs_authorization_service', models.CharField(blank=True, max_length=100, null=True)),
                ('tacacs_retries', models.PositiveSmallIntegerField(default=3)),
                ('tacacs_session_timeout', models.PositiveIntegerField(default=60)),
                ('tacacs_admin_group', models.CharField(blank=True, max_length=100, null=True)),
                ('tacacs_superuser_group', models.CharField(blank=True, max_length=100, null=True)),
                ('allow_local_superusers', models.BooleanField(default=True)),
                ('reachability_ping_enabled', models.BooleanField(default=True)),
                ('reachability_snmp_enabled', models.BooleanField(default=True)),
                ('reachability_ssh_enabled', models.BooleanField(default=False)),
                ('reachability_telemetry_enabled', models.BooleanField(default=False)),
                ('reachability_interval_minutes', models.PositiveIntegerField(default=10)),
                ('reachability_last_run', models.DateTimeField(blank=True, null=True)),
                ('snmp_version', models.CharField(choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], default='v2c', max_length=5)),
                ('snmp_port', models.PositiveIntegerField(default=161)),
                ('snmp_community', models.CharField(blank=True, default='public', max_length=128)),
                ('snmp_security_level', models.CharField(choices=[('noAuthNoPriv', 'noAuthNoPriv'), ('authNoPriv', 'authNoPriv'), ('authPriv', 'authPriv')], default='noAuthNoPriv', max_length=20)),
                ('snmp_username', models.CharField(blank=True, default='', max_length=128)),
                ('snmp_auth_protocol', models.CharField(blank=True, choices=[('md5', 'MD5'), ('sha', 'SHA')], default='sha', max_length=20)),
                ('snmp_auth_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('snmp_priv_protocol', models.CharField(blank=True, choices=[('des', 'DES'), ('aes128', 'AES-128')], default='aes128', max_length=20)),
                ('snmp_priv_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
