# Generated by Django 5.2.7 on 2025-12-11 14:35

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ssh', 'SSH'), ('snmp', 'SNMP'), ('http', 'HTTP/HTTPS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='dcim.site')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('tacacs_enabled', models.BooleanField(default=False)),
                ('tacacs_server_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('tacacs_port', models.PositiveIntegerField(default=49)),
                ('tacacs_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('tacacs_authorization_service', models.CharField(blank=True, max_length=100, null=True)),
                ('tacacs_retries', models.PositiveSmallIntegerField(default=3)),
                ('tacacs_session_timeout', models.PositiveIntegerField(default=60)),
                ('tacacs_admin_group', models.CharField(blank=True, max_length=100, null=True)),
                ('tacacs_superuser_group', models.CharField(blank=True, max_length=100, null=True)),
                ('allow_local_superusers', models.BooleanField(default=True)),
                ('reachability_ping_enabled', models.BooleanField(default=True)),
                ('reachability_snmp_enabled', models.BooleanField(default=True)),
                ('reachability_ssh_enabled', models.BooleanField(default=False)),
                ('reachability_netconf_enabled', models.BooleanField(default=False)),
                ('reachability_interval_minutes', models.PositiveIntegerField(default=10)),
                ('reachability_last_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='HTTPCredential',
            fields=[
                ('sitecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.sitecredential')),
                ('http_username', models.CharField(blank=True, max_length=100, null=True)),
                ('http_password', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('http_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('http_base_url', models.CharField(blank=True, max_length=300, null=True)),
                ('http_port', models.PositiveSmallIntegerField(default=443)),
                ('http_verify_tls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'HTTP/HTTPS Credential',
                'verbose_name_plural': 'HTTP/HTTPS Credentials',
            },
            bases=('accounts.sitecredential',),
        ),
        migrations.CreateModel(
            name='SNMPCredential',
            fields=[
                ('sitecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.sitecredential')),
                ('snmp_version', models.CharField(default='v2c', max_length=10)),
                ('snmp_port', models.PositiveSmallIntegerField(default=161)),
                ('snmp_community', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('snmp_security_level', models.CharField(blank=True, max_length=20, null=True)),
                ('snmp_username', models.CharField(blank=True, max_length=100, null=True)),
                ('snmp_auth_protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_auth_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('snmp_priv_protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('snmp_priv_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SNMP Credential',
                'verbose_name_plural': 'SNMP Credentials',
            },
            bases=('accounts.sitecredential',),
        ),
        migrations.CreateModel(
            name='SSHCredential',
            fields=[
                ('sitecredential_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.sitecredential')),
                ('ssh_username', models.CharField(max_length=100)),
                ('ssh_password', encrypted_model_fields.fields.EncryptedCharField()),
                ('ssh_port', models.PositiveSmallIntegerField(default=22)),
            ],
            options={
                'verbose_name': 'SSH Credential',
                'verbose_name_plural': 'SSH Credentials',
            },
            bases=('accounts.sitecredential',),
        ),
    ]
