# Generated by Django 5.2.7 on 2025-12-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='reachability_telemetry_enabled',
            new_name='reachability_netconf_enabled',
        ),
    ]
