# Generated by Django 5.2.7 on 2025-12-12 12:33

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_sshcredential_ssh_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshcredential',
            name='ssh_password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
