# Generated by Django 5.2.7 on 2026-02-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='topologyneighbor',
            new_name='topology_to_device__72bc02_idx',
            old_name='topology_nei_device__0f6a4f_idx',
        ),
        migrations.RenameIndex(
            model_name='topologyneighbor',
            new_name='topology_to_neighbo_f432a0_idx',
            old_name='topology_nei_neighbor_3b3e62_idx',
        ),
        migrations.RenameIndex(
            model_name='topologyneighbor',
            new_name='topology_to_protoco_c156f3_idx',
            old_name='topology_nei_protocol_4dd66b_idx',
        ),
    ]
