# Generated by Django 5.2.7 on 2025-12-17 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0005_alter_devicetype_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cidr', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('mgmt', 'Management'), ('loopback', 'Loopback'), ('transit', 'Transit'), ('infra', 'Infrastructure')], default='user', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ipam.prefix')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prefixes', to='dcim.site')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prefixes', to='dcim.vlan')),
            ],
            options={
                'ordering': ('site__name', 'cidr'),
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('dhcp', 'DHCP'), ('reserved', 'Reserved'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('vip', 'VIP'), ('loopback', 'Loopback')], default='secondary', max_length=20)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='dcim.interface')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ip_addresses', to='ipam.prefix')),
            ],
            options={
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='VRF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rd', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vrfs', to='dcim.site')),
            ],
            options={
                'ordering': ('site__name', 'name'),
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.AddField(
            model_name='prefix',
            name='vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prefixes', to='ipam.vrf'),
        ),
        migrations.AddConstraint(
            model_name='prefix',
            constraint=models.UniqueConstraint(condition=models.Q(('vrf__isnull', True)), fields=('cidr', 'site'), name='unique_prefix_cidr_site_no_vrf'),
        ),
        migrations.AddConstraint(
            model_name='prefix',
            constraint=models.UniqueConstraint(fields=('cidr', 'site', 'vrf'), name='unique_prefix_cidr_site_vrf'),
        ),
    ]
