# Generated by Django 5.2.7 on 2026-01-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, help_text='The hostname associated with this IP address', max_length=255, null=True, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('vip', 'VIP'), ('loopback', 'Loopback')], default='secondary', help_text='The role of this IP address', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dhcp', 'DHCP'), ('reserved', 'Reserved'), ('deprecated', 'Deprecated')], default='active', help_text='The operational status of this IP address', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='vrf',
            name='rd',
            field=models.CharField(blank=True, help_text='Route Distinguisher for the VRF', max_length=100, null=True, verbose_name='Route Distinguisher'),
        ),
    ]
