# Generated by Django 5.2.7 on 2025-12-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='site',
            field=models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn'), ('Gemeinsam', 'Gemeinsam')], default='Berlin', max_length=50),
        ),
    ]
