# Generated by Django 5.2.7 on 2026-01-05 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_alter_ipaddress_hostname_alter_ipaddress_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent prefix of this prefix', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ipam.prefix', verbose_name='Parent Prefix'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('mgmt', 'Management'), ('loopback', 'Loopback'), ('transit', 'Transit'), ('infra', 'Infrastructure')], default='user', help_text='The role of this prefix', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('reserved', 'Reserved'), ('deprecated', 'Deprecated')], default='active', help_text='The operational status of this prefix', max_length=20, verbose_name='Status'),
        ),
    ]
