# Generated by Django 5.2.7 on 2026-01-05 12:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0012_alter_devicetype_model'),
        ('ipam', '0003_alter_prefix_parent_alter_prefix_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary IP address on the interface'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='Reserved IP (not assignable automatically)'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Last time this IP was observed by automation', null=True),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Associated MAC address (if applicable)', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='MAC address must be in format AA:BB:CC:DD:EE:FF', regex='^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='address',
            field=models.GenericIPAddressField(help_text='IPv4 or IPv6 address', verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='hostname',
            field=models.CharField(blank=True, help_text='DNS hostname associated with this IP', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='interface',
            field=models.ForeignKey(blank=True, help_text='Interface this IP is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_addresses', to='dcim.interface'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='prefix',
            field=models.ForeignKey(help_text='Prefix this IP address belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ip_addresses', to='ipam.prefix'),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='role',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('vip', 'VIP'), ('loopback', 'Loopback')], default='secondary', help_text='Functional role of the IP address', max_length=20),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dhcp', 'DHCP'), ('reserved', 'Reserved'), ('deprecated', 'Deprecated')], default='active', help_text='Operational status of the IP address', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='ipaddress',
            constraint=models.UniqueConstraint(fields=('address', 'prefix'), name='uniq_ip_per_prefix'),
        ),
    ]
