# Generated by Django 5.2.7 on 2026-01-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_ipaddress_description_ipaddress_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefix',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('mgmt', 'Management'), ('loopback', 'Loopback'), ('transit', 'Transit'), ('infra', 'Infrastructure'), ('campus', 'Campus'), ('wan', 'WAN')], default='user', help_text='The role of this prefix', max_length=20, verbose_name='Role'),
        ),
    ]
