# Generated by Django 5.2.7 on 2025-11-12 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn')], max_length=50)),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('subnet', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Enter a valid subnet in CIDR notation (e.g., 10.228.0.0/24)', regex='^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}$')])),
                ('gateway', models.GenericIPAddressField(blank=True, null=True)),
                ('usage_area', models.CharField(choices=[('ACI', 'ACI'), ('Campus', 'Campus'), ('Management', 'Management'), ('PostProd', 'PostProd'), ('Autark', 'Autark'), ('BTSU', 'BTSU'), ('IP-Telefine', 'IP-Telefone'), ('Frei', 'Frei')], default='Frei', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['site', 'vlan_id'],
                'unique_together': {('site', 'vlan_id')},
            },
        ),
    ]
