# Generated by Django 5.2.7 on 2025-11-12 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='subnet',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid subnet in CIDR notation (e.g., 10.228.0.0/24)', regex='^(\\d{1,3}\\.){3}\\d{1,3}/\\d{1,2}$')]),
        ),
    ]
