# Generated by Django 5.2.7 on 2025-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlans', '0002_alter_vlan_name_alter_vlan_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='usage_area',
            field=models.CharField(choices=[('ACI', 'ACI'), ('Campus', 'Campus'), ('Management', 'Management'), ('PostProd', 'PostProd'), ('Autark', 'Autark'), ('BTSU', 'BTSU'), ('IP-Telefine', 'IP-Telefone'), ('Frei', 'Frei')], default='Frei', max_length=50, null=True),
        ),
    ]
