# Generated by Django 5.2.7 on 2025-11-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlans', '0003_alter_vlan_usage_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='site',
            field=models.CharField(choices=[('Berlin', 'Berlin'), ('Bonn', 'Bonn'), ('Gemeinsam', 'Gemeinsam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='usage_area',
            field=models.CharField(choices=[('ACI', 'ACI'), ('Campus', 'Campus'), ('Management', 'Management'), ('PostPro', 'PostPro'), ('Autark', 'Autark'), ('BTSU', 'BTSU'), ('IP-Telefine', 'IP-Telefone'), ('Frei', 'Frei'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', max_length=50, null=True),
        ),
    ]
