# Generated by Django 5.2.7 on 2025-12-11 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0001_initial'),
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('backup', 'Configuration Backup'), ('ztp', 'Zero Touch Provisioning'), ('cli', 'CLI Command Execution'), ('telemetry', 'Telemetry Polling'), ('reachability', 'Reachability Check')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(blank=True, null=True)),
                ('memory_usage', models.FloatField(blank=True, null=True)),
                ('uptime', models.BigIntegerField(blank=True, null=True)),
                ('interface_count', models.IntegerField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='dcim.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('params', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('log', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('devices', models.ManyToManyField(related_name='job_runs', to='dcim.device')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationjob')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name for this schedule (e.g. 'Reachability Poller').", max_length=100)),
                ('task_name', models.CharField(help_text="Fully-qualified Celery task path (e.g. 'automation.scheduler.check_devices_reachability').", max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('crontab', 'Crontab')], default='interval', max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='Interval in seconds (used when schedule_type=interval).', null=True)),
                ('minute', models.CharField(default='*', max_length=64)),
                ('hour', models.CharField(default='*', max_length=64)),
                ('day_of_week', models.CharField(default='*', max_length=64)),
                ('day_of_month', models.CharField(default='*', max_length=64)),
                ('month_of_year', models.CharField(default='*', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, help_text='Linked django-celery-beat PeriodicTask.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_schedule', to='django_celery_beat.periodictask')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'task_name')},
            },
        ),
    ]
