# Generated by Django 5.2.7 on 2025-12-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('dcim', '0005_alter_device_site_alter_vlan_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='devices',
            field=models.ManyToManyField(related_name='job_runs', to='dcim.device'),
        ),
    ]
