# Generated by Django 5.2.7 on 2025-12-16 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('dcim', '0005_alter_devicetype_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='automationjob',
            name='name',
        ),
        migrations.AddField(
            model_name='automationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='automationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='job_type',
            field=models.CharField(choices=[('config_backup', 'Configuration Backup'), ('reachability', 'Reachability Check'), ('telemetry', 'Telemetry Snapshot'), ('command', 'Run Command')], max_length=30),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='job_runs', to='dcim.device'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
