# Generated by Django 5.2.7 on 2025-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_automationjob_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
