# Generated by Django 5.2.7 on 2025-12-09 11:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_jobrun_created_at_alter_jobrun_devices'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name for this schedule (e.g. 'Reachability Poller').", max_length=100)),
                ('task_name', models.CharField(help_text="Fully-qualified Celery task path (e.g. 'automation.scheduler.check_devices_reachability').", max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('crontab', 'Crontab')], default='interval', max_length=20)),
                ('interval_seconds', models.PositiveIntegerField(blank=True, help_text='Interval in seconds (used when schedule_type=interval).', null=True)),
                ('minute', models.CharField(default='*', max_length=64)),
                ('hour', models.CharField(default='*', max_length=64)),
                ('day_of_week', models.CharField(default='*', max_length=64)),
                ('day_of_month', models.CharField(default='*', max_length=64)),
                ('month_of_year', models.CharField(default='*', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, help_text='Linked django-celery-beat PeriodicTask.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_schedule', to='django_celery_beat.periodictask')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'task_name')},
            },
        ),
    ]
