# Generated by Django 5.2.7 on 2025-11-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_reachability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduletype',
            options={'verbose_name': 'Device Module', 'verbose_name_plural': 'Device Modules'},
        ),
    ]
